apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qebi19t8k-python
  janus-idp.io/tekton: qebi19t8k-python
  backstage.io/kubernetes-id: qebi19t8k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qebi19t8k-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
